### ISSUE TITLE
use abbreviations for evidence codes

### ISSUE THREAD

**Issue by nlwashington** [SciGraph/golr-loader#11]
we've had a request to display the abbreviation label for "evidence" instead of the full label.  (see https://github.com/monarch-initiative/dipper/issues/177)

does this information come in the current golr, or do we need a special way of adding this at golr-generation time?  if it is already in the golr, then we need to move this ticket to the monarch-app layer.

This seems like it ought to be a configurable thing, where the label that is placed in golr may be the "label" by default, but could be a special synonym type.

**Comment by jnguyenx** [comment]
so we can either replace the existing label with a synonym, or add a new field like label_short (not sure that the current golr schema supports that though).

One concern is that there are many synonyms, how can we select the "right" one?

From SciGraph:

*http://www.geneontology.org/formats/oboInOwl#id              =[ECO:0000501]                               
                 
*http://www.w3.org/2000/01/rdf-schema#label                   =[evidence used in automatic assertion]    
                   
*iri                                                          =[http://purl.obolibrary.org/obo/ECO_0000501]               
  
*label                                                        =[evidence used in automatic assertion]                
       
*synonym                                                      =[inferred from electronic annotation],[IEA]

**Comment by cmungall** [comment]
In the yaml for the loader it's possible to map arbitrary APs into (I think) arbitrary Neo4j tags (currently: synonym, definition)

We would add a new tag for 'code' (or perhaps abbreviation)

The tricky part is that you have to inspect the axiom annotation to determine (note: axiom annotations get lost in Neo4j)

If this turns out to be too hard we can make a new annotation property in ECO

**Comment by nlwashington** [comment]
shouldn't the synonym have some kind of property to mark it as an abbreviation already?  it does not seem to be present in the graph: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/ECO:0000501.graphson?project=%2A

**Comment by cmungall** [comment]
You can see it here, but you don't see the axiom annotations in scigraph: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/ECO:0000501.json

It will probably be easiest to do this upstream
