### ISSUE TITLE
Add edge label to evidence graph

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/golr-loader#15]
It would be useful to have edge labels available when creating visuals of an evidence graph.

Getting labels for edges is currently a two step process: 
Get the iri for an edge
Find the node with the same iri property and get its label

Two ideas:
1. Add label property to edges for whole graph
2. Add labels only to evidence graph (as json) in golr json

**Comment by jnguyenx** [comment]
Some thoughts:

We can retrieve this information when the golr-loader runs, no need to add this in the graph itself.

The bbop graph json format has a field `meta` for edges, we can fiddle the label there.

**Comment by cmungall** [comment]
You could also return the object properties as nodes

**Comment by jnguyenx** [comment]
https://github.com/SciGraph/SciGraph/commit/a07566543ff84d978bff377c3a4d374637abfe69
