### ISSUE TITLE
Too many values for UnInvertedField faceting on field object_closure

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/golr-loader#44]
Solr-dev is currently returning an exception for any biolink call that facets over object_closures:
java.lang.IllegalStateException: Too many values for UnInvertedField faceting on field object_closure

We've appeared to have hit some limit, but it's not obvious from looking at the data:
Solr Production
Total Docs: 37502996
Unique values in object_closure: 4005165

Solr Dev:
Total Docs: 38759008
Unique values in object_closure: 4350271

It's also possible the limit is based on the number of values per a single document, but this is harder to gather without iterating over each document.

Related:
https://issues.apache.org/jira/browse/SOLR-11240

Possible solutions:
- Use facet.method=enum, but this is about 10x slower than method=fc
- Use docValues - https://lucene.apache.org/solr/guide/6_6/docvalues.html, requires small update to golr schema, https://github.com/berkeleybop/golr-schema
- Update solr to 7+
- Reindex and hope for the best, possible that small data changes could affect these counts

cc @kltm @doctorbud @deepakunni3

**Comment by cmungall** [comment]
4m is more than I would have expected, iI guess this is because genes, variants, etc make their way into the closure?

**Comment by kshefchek** [comment]
it does seem high, I could put the values in a file so we can debug.

**Comment by kshefchek** [comment]
Another solution is to only close over equivalentClass for entities such as genes, variants, etc.

**Comment by kltm** [comment]
Kent,

It may also be that the resources applied to the Solr instance are
insufficient to build the necessary caches. Would you have taken a look
already at the admin/stats page (e.g. fieldValueCache)?

 https://wiki.apache.org/solr/SimpleFacetParameters#facet.method
 https://wiki.apache.org/solr/SolrCaching#fieldValueCache

Did this error crop up after a data load or schema change, or has it
just not been noticed until now?

Cheers,

-Seth

**Comment by kshefchek** [comment]
This occurred after a new data load, and we've tried increasing the memory.

some more stats on the object_closure field:
sum: 819945513
max: 648
mean: 21.15496642741734

All values:
[object_closure.txt.gz](https://github.com/SciGraph/golr-loader/files/2963796/object_closure.txt.gz)

![solr-admin](https://user-images.githubusercontent.com/1467299/54316935-1969ee00-459f-11e9-8b53-f380d362fc46.png)

Nothing I can see in the logs when the server is starting up.

**Comment by kshefchek** [comment]
Here is some more info after reindexing:

1. Indexed on monarch5, moved files to solr-dev
- facets on object_closure work
2. Optimized index
- Exception when faceting on object_closure

So oddly this is related to optimizing on the solr-dev VM, versus optimizing on monarch5, I changed this as we were running out of disk space on monarch5.

**Comment by kshefchek** [comment]
I'm uncertain of the cause of this, but at least understand how to avoid it.  Propose we close since it's no longer an issue.

**Comment by kshefchek** [comment]
this is rearing its head again, although not for every load, and it seems re-indexing fixes it.  Will play around with memory config.

**Comment by cmungall** [comment]
does this help?
https://lucene.472066.n3.nabble.com/java-lang-IllegalStateException-Too-many-values-for-UnInvertedField-faceting-on-field-content-td4218197.html

**Comment by kshefchek** [comment]
I have to look back through my notes to see if I tried docValues.  This has also been fixed in Solr 7 and above so another reason to push for an update: https://issues.apache.org/jira/browse/SOLR-11240
