### ISSUE TITLE
Unable to get gene phenotype relationships in current view

### ISSUE THREAD

**Issue by kshefchek** [SciGraph/golr-loader#5]
I'm unable to fetch gene phenotype associations from the current GOlr view, although I can get them using the SciGraph dynamic services, for example: http://duckworth.crbs.ucsd.edu:9000/scigraph/dynamic/features/NCBIGene:6469/phenotypes

Example Golr attempt:
[object_category = phenotype, subject_closure = NCBIGene:6469 ](http://geoffrey.crbs.ucsd.edu:8080/solr/golr/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&fq=subject_closure:%22NCBIGene:6469%22&fq=object_category:%22phenotype%22&facet.field=subject_category&facet.field=subject_taxon&facet.field=subject_closure_label&facet.field=relation_closure_label&facet.field=qualifier&facet.field=evidence_closure_label&facet.field=object_category&facet.field=object_closure_label&q=*:*&packet=1)

**Comment by ccondit** [comment]
This is most likely because geoffrey is reloading to fix #2. I think that pair hasn't reloaded yet.
