### ISSUE TITLE
Orphanet disease-phenotype associations not loading into Golr?

### ISSUE THREAD

**Issue by cmungall** [SciGraph/golr-loader#7]
From: monarch-initiative/hpo-annotation-data#3 

Solr has no results:

http://geoffrey.crbs.ucsd.edu:8080/solr/golr/select/?q=*:*&fq=object_category:phenotype&fq=subject:%22Orphanet:881%22&rows=10&facet=true&facet.field=object_category&facet.field=subject_category&wt=json

But the data is in SciGraph:

http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/diseases/Orphanet:881/phenotypes.json

However, I noticed the Orphanet node lacks a category (should be disease) - is this the cause?

cc @mellybelly

**Comment by ccondit** [comment]
@cmungall - yes. The query to load this Golr index is expecting that the subject has category 'disease' (either `rdf:type` or `rdfs:subClassOf*` of disease).

**Comment by cmungall** [comment]
How do we fix this? AFAICT it's a transitive subclass of disease on monarch.owl and SG

**Comment by ccondit** [comment]
Strange. I don't see that here:
http://rosie.crbs.ucsd.edu:9000/scigraph/graph/neighbors/Orphanet:881.json?relationshipType=subClassOf

and I don't see this individual in monarch.owl.

Is http://www.orpha.net/ORDO/Orphanet_881 the expected IRI?

**Comment by cmungall** [comment]
You're right. The issue here is that the Orphanet class is only linked into the mondo hierarchy through a non-logical dbxref. I will propose a separate solution.

**Comment by kshefchek** [comment]
Seems this works now https://monarchinitiative.org/disease/ORPHA:881 we likely just forgot to close
